---

### install requirements

- apt: name={{item}} state=present
  sudo: yes
  with_items:
    - nodejs
    - rubygems
    - ruby1.9.1
    - git
    - g++-4.6

- shell: rm /usr/bin/ruby; cp /usr/bin/ruby1.9.1 /usr/bin/ruby
  sudo: yes
- shell: rm /usr/bin/gem; cp /usr/bin/gem1.9.1 /usr/bin/gem
  sudo: yes

- gem: name={{item}} state=present user_install=no
  sudo: yes
  with_items:
    - bundler
    - dashing
    - json

### generate or git clone

- shell: rm -rf /home/pi/dashboard

- git: repo="{{dashing_git_repo}}"
       dest=/home/pi/dashboard
       update=yes
       accept_hostkey=yes
  when: dashing_git_repo is defined

- shell: dashing new dashboard
  args:
    chdir: /home/pi
    creates: /home/pi/dashboard
  when: dashing_git_repo is undefined

### install more stuff

- shell: bundle
  args:
    chdir: /home/pi/dashboard
