---

- shell: raspi-config --expand-rootfs; touch /home/pi/.fs_is_expanded
  args:
    creates: /home/pi/.fs_is_expanded

- lineinfile: dest=/boot/config.txt line="{{item}}" state=present
  with_items:
    - "disable_overscan = 0"
    - "overscan_left = -48"
    - "overscan_right = -48"
    - "overscan_top = -48"
    - "overscan_bottom = -48"
    - "hdmi_group = 2"
    - "hdmi_mode = 82"
    - "arm_freq = 1000"
    - "core_freq = 500"
    - "sdram_freq = 600"
    - "over_voltage = 6"
    - "initial_turbo = 0"

- apt: update_cache=yes cache_valid_time=86400
- apt: upgrade=dist
- apt: upgrade=full

- apt: name={{item}} state=latest
  with_items:
    - x11vnc
    - midori
    - matchbox-window-manager

- copy: src=stuff/xinitrc dest=/home/pi/.xinitrc owner=pi
- lineinfile: dest=/etc/rc.local line="su -l pi -c startx"
              state=present insertbefore="exit"
