---

- shell: raspi-config --expand-rootfs; touch /home/pi/.fs_is_expanded
  args:
    creates: /home/pi/.fs_is_expanded

- copy: src=stuff/config.txt dest=/boot/config.txt

- apt: update_cache=yes cache_valid_time=86400
- apt: upgrade=dist
- apt: upgrade=full

- apt: name={{item}} state=latest
  with_items:
    - x11vnc
    - midori
    - matchbox-window-manager
    - rpi-update

- shell: rpi-update

- name: copy xinitrc
  template: stuff/xinitrc
  dest: /home/pi/.xinitrc
  owner: pi

- lineinfile: dest=/etc/rc.local line="su -l pi -c startx"
              state=present insertbefore="exit"
