xset s off
xset -dpms
xset s noblank
x11vnc -display :0 -forever -shared &
matchbox-window-manager &
chromium-browser --no-sandbox --noerrdialogs --start-fullscreen --start-maximized --disable-notifications --disable-infobars --kiosk --incognito '{{ dashboard_url }}' -- -nocursor
